#!/bin/sh /etc/rc.common

START=99

start() {
sleep 10
frpnum=$(echo "$(uci get network.lan_eth0_1_dev.macaddr)" | tr -d ":" )
uci set frp.@proxy[0].remark=$frpnum
uci set frp.@proxy[0].subdomain=$frpnum
uci commit frp

rm -rf /etc/config/passwall_show
rm -rf /etc/config/fileassistant_show
}
